### ISSUE TITLE
MacOS brew install jpeg-xl error

### ISSUE THREAD

**Issue by martinsluka** [libjxl/libjxl#2461]
brew install jpeg-xl

==> Upgrading jpeg-xl
  0.6.1_1 -> 0.8.1_2 

==> cmake -S . -B build -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=ON -DJPEGXL
==> cmake --build build
Last 15 lines from /Users/studiosluka_3/Library/Logs/Homebrew/jpeg-xl/02.cmake:
<stdin>:16089:2: error: instruction requires: AVX-512 ISA
        vfmadd132ps     %zmm0, %zmm5, %zmm2
        ^
<stdin>:16090:2: error: instruction requires: AVX-512 ISA
        vaddps  %zmm2, %zmm3, %zmm0
        ^
<stdin>:16091:2: error: instruction requires: AVX-512 ISA
        vfmadd132ps     %zmm7, %zmm4, %zmm0
        ^
<stdin>:16092:2: error: instruction requires: AVX-512 ISA
        vmovaps %zmm0, (%rbx,%rax)
        ^
make[2]: *** [lib/CMakeFiles/jxl_dec-obj.dir/jxl/convolve_separable5.cc.o] Error 1
make[1]: *** [lib/CMakeFiles/jxl_dec-obj.dir/all] Error 2
make: *** [all] Error 2

**Environment**
 - OS: MacOS 10.13.6
 - Compiler version:cmake version 3.26.3
 - CPU type: Intel Core 2 Duo
 - cjxl/djxl version string: [e.g. cjxl [v0.3.7 | SIMD supported: SSE4,Scalar]]

**Additional context**

**Comment by Ultrium2000** [comment]
I have the same problem! Please help us!

**Comment by jmroot** [comment]
Looks similar to the issues fixed by #2383 and #2387. Those changes are applied in MacPorts, which has successful builds on all tested OS versions: https://ports.macports.org/port/libjxl/details/

**Comment by Ultrium2000** [comment]
Thanks for the help!


> Looks similar to the issues fixed by #2383 and #2387. Those changes are applied in MacPorts, which has successful builds on all tested OS versions: https://ports.macports.org/port/libjxl/details/

Thanks for the help

**Comment by mo271** [comment]
Is this still an issue, or can this be closed here?

**Comment by martinsluka** [comment]
Still issue of older versions of MacOS. Macport instalation has another problems. jpeg-xl is a new experimental compression format, so there is not any reason to be included in Survey.

Martin

**Comment by crackajack77** [comment]
yes, still a problem also here on 10.14 with brew, unfortunately - since it's a dependency for ffmpeg this is a big issue :)

**Comment by kli0rf** [comment]
Any updates on this?

**Comment by webamadou** [comment]
Any one has a fix for this. 
Installing PHP is blocked while trying to install jpeg-xl.
Installing php@8.1 dependency: jpeg-xl
```Error: An exception occurred within a child process:
  CompilerSelectionError: jpeg-xl cannot be built with any available compilers.
Install GNU's GCC:
  brew install gcc
```
This is on a iMac 10.13 (I know it's old)

**Comment by emyu01** [comment]
Having same issue, any workaround?

**Comment by martinsluka** [comment]
It is version of MacOS. The latest versions have no problem with instalation. MartinOdesláno z iPhonu29. 10. 2023 v 2:04, Umar ***@***.***>:﻿
Having same issue, any workaround?

**Comment by drone540** [comment]
I also have this problem

I'm having issues related to AVX512 / Clang

I noticed that MacPorts has all the listed fixes here if that helps.

https://github.com/macports/macports-ports/tree/master/graphics/libjxl/files

I noticed some previous attempts to fix [Clang](https://github.com/libjxl/libjxl/pull/2383) and [AVX512](https://github.com/libjxl/libjxl/pull/2387) already. But I believe it's incomplete

Unfortunately I don't have my log file at the moment (as I was testing in a VM) to know the exact offending file - (Will edit this post in the morning). 
But I believe the error I have that there is no clang check added to the file: lib/jxl/image.cc.orig

As shown in the macports clang fix.

**Comment by Norb48** [comment]
Can someone explain me please? I installed all dependencies listed in homebrew independently for jpeg-xl but still can't install jpeg-xl

**Comment by fefe79** [comment]
> Can someone explain me please? I installed all dependencies(without any problem) listed in homebrew independently for jpeg-xl but still can't install jpeg-xl on macos 10.15.7

Yeah, it does not compile for me either, although I get a different error:
-----------------------------------------------------------------------------
`==> Upgrading jpeg-xl
  0.9.1 -> 0.10.1 

==> cmake -S . -B build -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=ON -DJPEGXL_FORCE_SYSTEM_HWY=ON -DJPEGXL_ENABLE_JNI=OFF -DJPEGXL_ENABLE_JPEGLI=OFF -DJPEGXL_ENABLE_SKCMS=OFF -DJPEGXL_VERSION=0.10.1 -DJPEGXL_ENABLE_MAN
==> cmake --build build
Last 15 lines from /Users/usr/Library/Logs/Homebrew/jpeg-xl/02.cmake:
/tmp/jpeg-xl-20240306-95154-8l2t61/libjxl-0.10.1/lib/jxl/coeff_order.h:33:42: error: constexpr function never produces a constant expression [-Winvalid-constexpr]
static JXL_MAYBE_UNUSED constexpr size_t CoeffOrderOffset(size_t order,
                                         ^
/tmp/jpeg-xl-20240306-95154-8l2t61/libjxl-0.10.1/lib/jxl/coeff_order.h:35:10: note: non-constexpr function 'operator[]' cannot be used in a constant expression
  return kCoeffOrderOffset[3 * order + c] * kDCTBlockSize;
         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/array:195:21: note: declared here
    const_reference operator[](size_type __n) const _NOEXCEPT {return __elems_[__n];}
`
-----------------------------------------------------------------------------

**Comment by eustas** [comment]
Will fix `CoeffOrderOffset` soon. This works with modern compilers, but alas, we have to support all kinds of nonsense...

**Comment by martinsluka** [comment]
It is because system version. The newest versions are without problem. Anyway you may install a boot loader called OpenCore Legacy on Intel Mac and install Sonoma. MartinOdesláno z iPhonu6. 3. 2024 v 11:25, Eugene Kliuchnikov ***@***.***>:﻿
Will fix CoeffOrderOffset soon. This works with modern compilers, but alas, we have to support all kinds of nonsense...

**Comment by Norb48** [comment]
> > Can someone explain me please? I installed all dependencies(without any problem) listed in homebrew independently for jpeg-xl but still can't install jpeg-xl on macos 10.15.7
> 
> I could upgrade jpeg-xl from 0.9.1 -> 0.10.1
> 
> ## Here is what I did:
> I Installed the latest gcc: `brew install gcc`
> 
> Then I run: `brew install jpeg-xl --force --cc gcc-13`

I try your suggestion one part worked ,installing  `gcc` and then                                                                                                              Error: An exception occurred within a child process:
  RuntimeError: /usr/local/opt/cmake not present or broken
Please reinstall cmake. Sorry :(
lucilalico@lucilas-iMac ~ % 
it is like going around , spinning wheel

**Comment by fefe79** [comment]
> @fefe79 >
> 
> I try your suggestion,one part worked ,installing `gcc` and then `Error: An exception occurred within a child process: RuntimeError: /usr/local/opt/cmake not present or broken Please reinstall cmake. Sorry :(` I installed `cmake` as i said all dependencies for jpeg-xl it is like going around , spinning wheel

Make sure The latest available Command Line Tools for Xcode - v12.4 installed and working, or re-install it if needed and try it again to install jpeg-xl.

**Comment by Norb48** [comment]
@fefe79 That's my version of `xcode-select version 2373` . I checked it and it seems like it's version for xcode 12.1 .
I don't know why I can't upgrade it to new version for xcode 12.4

**Comment by fefe79** [comment]
> @fefe79 That's my version of `xcode-select version 2373` . I checked it and it seems like it's version for xcode 12.1 .
> I don't know why I can't upgrade it to new version for xcode 12.4

Here is the official Download link for the 12.4:
[https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg](https://download.developer.apple.com/Developer_Tools/Command_Line_Tools_for_Xcode_12.4/Command_Line_Tools_for_Xcode_12.4.dmg)

**Comment by Norb48** [comment]
@fefe79 thanks `xcode clt for 12.4 ` installed, so easy https://developer.apple.com/download/all/ for all tools

**Comment by fefe79** [comment]
> @fefe79 thanks `xcode clt for 12.4 ` installed, so easy https://developer.apple.com/download/all/ for all tools, but jpeg-xl still not .still error from brew :(

Try to Install latest version of gcc v13.2.0:
brew install gcc

Then make sure, open a new terminal, and run:
brew install jpeg-xl --force --cc gcc-13

Or you can try to edit yous .bash_profile and add to the end of it (and in a new terminal run the brew install jpeg-xl....):
alias gcc='gcc-13'
alias cc='gcc-13'
alias g++='g++-13'
alias c++='c++-13

**Comment by Gertcha** [comment]
👆 thanks this worked for me, same issue too: error on upgrade with Catalina 15.7

**Comment by Norb48** [comment]
@fefe79  thanks finally done ,it works👍 , can carry on with installing PHP , I expect more problems

**Comment by Eden-tran** [comment]
@fefe79 thankss for you solution. I make it with that.

**Comment by timeimp** [comment]
> Will fix `CoeffOrderOffset` soon. This works with modern compilers, but alas, we have to support all kinds of nonsense...

I installed Clang 17 from home brew on my Mac (10.14 Mojave) and updated all the references to use it and NOT any local system items wherever possible. 

Is this a clang-specific error, or is GCC doing something specific? 

I'm stuck building jpeg-xl and installing from brew on this constexpr.

**Comment by timeimp** [comment]
@fefe79's suggestion to use GCC-13 worked. 

Anyone who finds this page: try using GCC as the compiler instead of clang.

**Comment by wyatt-wong** [comment]
> > Can someone explain me please? I installed all dependencies(without any problem) listed in homebrew independently for jpeg-xl but still can't install jpeg-xl on macos 10.15.7
> 
> I could upgrade jpeg-xl from 0.9.1 -> 0.10.1
> 
> ## Here is what I did:
> I Installed the latest gcc: `brew install gcc`
> 
> Then I run: `brew install jpeg-xl --force --cc gcc-13`

Thanks. Your methods work for me.

I am using macOS Catalina 10.15.7 and successfully upgraded jpeg-xl from 0.8.2_1 -> 0.10.2

`wyattwong@MacBookPro Downloads % brew install jpeg-xl --force --cc gcc-13
jpeg-xl 0.8.2_1 is already installed but outdated (so it will be upgraded).
Warning: You passed `--cc=gcc-13`.
It is expected behaviour that some formulae will fail to build in this unsupported configuration.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

Warning: You are using macOS 10.15.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Fetching jpeg-xl
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/c8a728b18777
Already downloaded: /Users/wyattwong/Library/Caches/Homebrew/downloads/8d851a35ad8254c0db182ce4f9cbcd9ffa91d399ddb972b3b7497f6c18e9ef0b--jpeg-xl.rb
==> Cloning https://github.com/webmproject/sjpeg.git
Updating /Users/wyattwong/Library/Caches/Homebrew/jpeg-xl--sjpeg--git
origin/HEAD set to master
refs/remotes/origin/master
==> Checking out revision e5ab13008bb214deb66d5f3e17ca2f8dbff150bf
HEAD is now at e5ab130 Merge pull request #119 from szabadka/master
HEAD is now at e5ab130 Merge pull request #119 from szabadka/master
==> Downloading https://github.com/libjxl/libjxl/archive/refs/tags/v0.10.2.tar.gz
Already downloaded: /Users/wyattwong/Library/Caches/Homebrew/downloads/1d8fc35d3c7e4ab3922e18bba9e7ce42a291b9a6605d65cfbb6ce93f064c2f1a--libjxl-0.10.2.tar.gz
==> Upgrading jpeg-xl
  0.8.2_1 -> 0.10.2 
==> cmake -S . -B build -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=O
==> cmake --build build
==> cmake --build build --target install
🍺  /usr/local/Cellar/jpeg-xl/0.10.2: 47 files, 5.2MB, built in 4 minutes 9 seconds
==> Running `brew cleanup jpeg-xl`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /usr/local/Cellar/jpeg-xl/0.8.2_1... (43 files, 19.4MB)
Removing: /Users/wyattwong/Library/Caches/Homebrew/jpeg-xl--0.9.1.tar.gz... (1.8MB)
Warning: The following dependents of upgraded formulae are outdated but will not
be upgraded because they are not bottled:
  libheif
  libavif
  aom
  imagemagick
==> No outdated dependents to upgrade!
==> Checking for dependents of upgraded formulae...
Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
==> No broken dependents to reinstall!`

**Comment by orange2013** [comment]
> > > Can someone explain me please? I installed all dependencies(without any problem) listed in homebrew independently for jpeg-xl but still can't install jpeg-xl on macos 10.15.7
> > 
> > 
> > I could upgrade jpeg-xl from 0.9.1 -> 0.10.1
> > ## Here is what I did:
> > I Installed the latest gcc: `brew install gcc`
> > Then I run: `brew install jpeg-xl --force --cc gcc-13`
> 
> Thanks. Your method work for me.
> 
> I am using macOS Catalina 10.15.7 and successfully upgraded jpeg-xl from 0.8.2_1 -> 0.10.2
> 
> `wyattwong@MacBookPro Downloads % brew install jpeg-xl --force --cc gcc-13 jpeg-xl 0.8.2_1 is already installed but outdated (so it will be upgraded). Warning: You passed `--cc=gcc-13`. It is expected behaviour that some formulae will fail to build in this unsupported configuration. It is expected behaviour that Homebrew will be buggy and slow. Do not create any issues about this on Homebrew's GitHub repositories. Do not create any issues even if you think this message is unrelated. Any opened issues will be immediately closed without response. Do not ask for help from Homebrew or its maintainers on social media. You may ask for help in Homebrew's discussions but are unlikely to receive a response. Try to figure out the problem yourself and submit a fix as a pull request. We will review it but may or may not accept it.
> 
> Warning: You are using macOS 10.15. We (and Apple) do not provide support for this old version. It is expected behaviour that some formulae will fail to build in this old version. It is expected behaviour that Homebrew will be buggy and slow. Do not create any issues about this on Homebrew's GitHub repositories. Do not create any issues even if you think this message is unrelated. Any opened issues will be immediately closed without response. Do not ask for help from Homebrew or its maintainers on social media. You may ask for help in Homebrew's discussions but are unlikely to receive a response. Try to figure out the problem yourself and submit a fix as a pull request. We will review it but may or may not accept it.
> 
> ==> Fetching jpeg-xl ==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/c8a728b18777 Already downloaded: /Users/wyattwong/Library/Caches/Homebrew/downloads/8d851a35ad8254c0db182ce4f9cbcd9ffa91d399ddb972b3b7497f6c18e9ef0b--jpeg-xl.rb ==> Cloning https://github.com/webmproject/sjpeg.git Updating /Users/wyattwong/Library/Caches/Homebrew/jpeg-xl--sjpeg--git origin/HEAD set to master refs/remotes/origin/master ==> Checking out revision e5ab13008bb214deb66d5f3e17ca2f8dbff150bf HEAD is now at e5ab130 Merge pull request #119 from szabadka/master HEAD is now at e5ab130 Merge pull request #119 from szabadka/master ==> Downloading https://github.com/libjxl/libjxl/archive/refs/tags/v0.10.2.tar.gz Already downloaded: /Users/wyattwong/Library/Caches/Homebrew/downloads/1d8fc35d3c7e4ab3922e18bba9e7ce42a291b9a6605d65cfbb6ce93f064c2f1a--libjxl-0.10.2.tar.gz ==> Upgrading jpeg-xl 0.8.2_1 -> 0.10.2 ==> cmake -S . -B build -DJPEGXL_FORCE_SYSTEM_BROTLI=ON -DJPEGXL_FORCE_SYSTEM_LCMS2=O ==> cmake --build build ==> cmake --build build --target install 🍺 /usr/local/Cellar/jpeg-xl/0.10.2: 47 files, 5.2MB, built in 4 minutes 9 seconds ==> Running `brew cleanup jpeg-xl`... Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`). Removing: /usr/local/Cellar/jpeg-xl/0.8.2_1... (43 files, 19.4MB) Removing: /Users/wyattwong/Library/Caches/Homebrew/jpeg-xl--0.9.1.tar.gz... (1.8MB) Warning: The following dependents of upgraded formulae are outdated but will not be upgraded because they are not bottled: libheif libavif aom imagemagick ==> No outdated dependents to upgrade! ==> Checking for dependents of upgraded formulae... Disable this behaviour by setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK. Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`). ==> No broken dependents to reinstall!`

It's work for macOS 10.14

**Comment by makemovesthatmatter** [comment]
> > Can someone explain me please? I installed all dependencies(without any problem) listed in homebrew independently for jpeg-xl but still can't install jpeg-xl on macos 10.15.7
> 
> I could upgrade jpeg-xl from 0.9.1 -> 0.10.1
> 
> ## Here is what I did:
> I Installed the latest gcc: `brew install gcc`
> 
> Then I run: `brew install jpeg-xl --force --cc gcc-13`

I am using Catlina 10.15.7, and this fix did not completely work by itself. What I did find was a fix on this thread:

https://stackoverflow.com/questions/72532485/homebrew-installation-error-not-a-valid-ref-refs-remotes-origin-master

Here is the reply from [Sourabh Shekhar](https://stackoverflow.com/users/1292218/sourabh-shekhar):
```

This worked on M1.

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
git config --global core.compression 0
git config --global http.postBuffer 1048576000
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

```
Along with this, I had to force install python 3.12, along with pip install setuptools for some reason too.

Although I do not have an M1 chip, after I ran this code, along with force installed gcc as mentioned above - it worked!

**Comment by dylanbarwick** [comment]
> ## Here is what I did:
> 
> I Installed the latest gcc: `brew install gcc`
> 
> Then I run: `brew install jpeg-xl --force --cc gcc-13`

FWIW, my local installation complained about forcing jpeg-xl to install under gcc-13 since it wasn't installed so I ran `brew install gcc@13` to install that version specifically and now it works. I just successfully installed php@8.2 on my Catalina-flavoured MacBook Pro.

**Comment by dtsosie** [comment]
I am currently running Catalina with newest Xcode compatible with it. My magic commands were:

brew install curl
brew install gcc
brew install jpeg-xl --force --cc gcc-14
brew install php@8.2
